services:
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - ./:/usr/src/app
    env_file:
    - .env
    ports:
      - 4000:4000
